"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
    <Navbar></Navbar>
        <main className="min-h-screen">
          {children}
        </main>
        
        
          <footer className="footer sm:footer-horizontal footer-center bg-base-300 text-primary p-4">
  <aside>
    <p>Copyright © {new Date().getFullYear()} - All right reserved by My-shop</p>
  </aside>
</footer>
        </SessionProvider>
        
       
      </body>
    </html>
  );
}
